//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.employees1 = new HashSet<employee>();
        }
    
        public int employee_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public System.DateTime birth_date { get; set; }
        public Nullable<int> enroll_no { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string personal_email { get; set; }
        public string work_email { get; set; }
        public Nullable<System.DateTime> employed_date { get; set; }
        public bool active { get; set; }
        public Nullable<int> nationality_id { get; set; }
        public string password { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_created { get; set; }
        public int role_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<double> Salary { get; set; }
        public string marital_status { get; set; }
    
        public virtual ICollection<employee> employees1 { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
